### ISSUE TITLE
Argument of type 'UDPTransport' is not assignable to parameter of type 'TransportStream'

### ISSUE THREAD

**Issue by nikkonrom** [raz6tamir/UDP-transport-winston#13]
### Environment details

- OS: macOS 10.15.7
- Node.js version: 14.13.0
- npm version: 6.14.18
- typscript version: 4.0.3
- winston version: 3.3.3 (also reproducable with 3.2.1)
- udp-transport-winston version: 1.1.7

### Steps to reproduce

1. Try setting up winston:
```typescript
import {config} from './config'
import {createLogger, transports, Logger} from 'winston'
import {UDPTransport} from 'udp-transport-winston';

const logger: Logger = createLogger({
  level: config.get('logging.level'),
  exitOnError: false
})
logger.add(new UDPTransport({
    host: config.get('logging.transports.udp.host'),
    port: config.get('logging.transports.udp.port')
  }))
```
2. Typescript throws an error:
```
error TS2345: Argument of type 'UDPTransport' is not assignable to parameter of type 'TransportStream'.
  Type 'UDPTransport' is missing the following properties from type 'TransportStream': writable, writableEnded, writableFinished, writableHighWaterMark, and 29 more.
```

### Fix

The problem is that `winston-transport` defines the export of `TransportStream` via `export =`.

Changing the typings of `udp-transport-winston/src/udp-transport.ts` resolves the problem:
```diff
-import * as Transport from 'winston-transport';
+import Transport = require('winston-transport');
```

**Similar issues:** https://github.com/googleapis/nodejs-logging-winston/issues/129, https://github.com/microsoft/TypeScript/issues/29505, https://github.com/googleapis/nodejs-logging-winston/issues/342
**See also:** [typescript documentation on AMD and CommonJS modules](https://www.typescriptlang.org/docs/handbook/modules.html#testts-2)

**Comment by raz6tamir** [comment]
Thank you for the issue. I will look into it.
Seems this is related to typescript v4.
